[package]
name = "tennis-kata"
version = "0.1.0"
authors = ["Francesco Gualazzi <francesco.gualazzi@lastminute.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
